encoding: utf-8

#url: http://woniu.me
name: 蜗牛的部落格

markdown: kramdown

# code highlighting
pygments: true

# standard jekyll configuration options
exclude: ['Rakefile', 'README.md', 'config.rb']

# configuration required for some pages

#domain: http://woniu.me
title: 蜗牛的部落格
author: __蜗牛__
email: peng_du2007@qq.com