encoding: utf-8

#url: http://ioioj5.github.io
url: https://www.woniu.me
name: 蜗牛的部落格

markdown: kramdown

# code highlighting
pygments: true

# standard jekyll configuration options
exclude: ['Rakefile', 'README.md', 'config.rb']

# configuration required for some pages

#domain: http://ioioj5.github.io
domain: https://www.woniu.me
title: 蜗牛的部落格|江湖人送匪号,血手人屠.
author: __都非拉得
email: peng_du2007@qq.com
